[features]
seeds = false
skip-lint = false
[programs.localnet]
my_market = "9vRQ68z2Mz5eZkneiwTDMni9AHtfCEV72HRgQgY7Jsap"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gleblevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
